<?php

$teachers_creteil = array("Arnaud", "Cédric", "Driko", "Jérôme", "Léo", "Mario", "Séna", "Tefy", "Véronique", "MJ", "Sébastien", "Stéphane");
$teachers_bodyvip = array("Arnaud", "Cédric", "Driko", "Greg", "Jérôme", "Léo", "Mario", "MJ", "Séna", "Tefy", "Véronique");

$lessons = array(
		'creteil_confirmes_2014' => array('belts' => array('marron', 'noire'),
						'name' => "Confirmés Créteil 2015-2015",
                				'days_of_week' => array(2,4),
                				'start_date' => "2014-09-10",
						'end_date' => "2015-06-20",
						'teachers' => $teachers_creteil,
						'locale' => 'fr_FR',
						),
		'creteil_intermediaires_2014' => array('belts' => array('verte', 'bleue'),
						'name' => "Intermédiaires Créteil 2015-2015",
                				'days_of_week' => array(2,5),
                				'start_date' => "2014-09-10",
						'end_date' => "2015-06-20",
						'teachers' => $teachers_creteil,
						'locale' => 'fr_FR',
						),
		'creteil_debutants_2014' => array('belts' => array('jaune', 'orange'),
						'name' => "Débutants Créteil 2015-2015",
                				'days_of_week' => array(2,4),
                				'start_date' => "2014-09-10",
						'end_date' => "2015-06-20",
						'teachers' => $teachers_creteil,
						'locale' => 'fr_FR',
						),
		'beuvin_2014' => array('belts' => array('jaune', 'orange', 'verte', 'bleue', 'marron', 'noire'),
						'name' => "Beuvin 2015-2015",
                				'days_of_week' => array(3),
                				'start_date' => "2014-09-10",
						'end_date' => "2015-06-20",
						'teachers' => $teachers_creteil,
						'locale' => 'fr_FR',
						),
		'bodyvip_confirmes_2014' => array('belts' => array('marron', 'noire'),
						'name' => "Confirmés Body VIP 2015-2015",
                				'days_of_week' => array(3,6),
                				'start_date' => "2014-09-10",
						'end_date' => "2015-06-20",
						'teachers' => $teachers_bodyvip,
						'locale' => 'fr_FR',
						),
		'bodyvip_intermediaires_2014' => array('belts' => array('verte', 'bleue'),
						'name' => "Intermédiaires Body VIP 2015-2015",
                				'days_of_week' => array(2,3,6),
                				'start_date' => "2014-09-10",
						'end_date' => "2015-06-20",
						'teachers' => $teachers_bodyvip,
						'locale' => 'fr_FR',
						),
		'bodyvip_debutants_2014' => array('belts' => array('jaune', 'orange'),
						'name' => "Débutants Body VIP 2015-2015",
                				'days_of_week' => array(2,3,6),
                				'start_date' => "2014-09-10",
						'end_date' => "2015-06-20",
						'teachers' => $teachers_bodyvip,
						'locale' => 'fr_FR',
						),


		'creteil_confirmes_2013' => array('belts' => array('marron', 'noire'),
						'name' => "Confirmés Créteil 2013-2014",
                				'days_of_week' => array(2,4),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $teachers_creteil,
						'locale' => 'fr_FR',
						),
		'creteil_intermediaires_2013' => array('belts' => array('verte', 'bleue'),
						'name' => "Intermédiaires Créteil 2013-2014",
                				'days_of_week' => array(2,5),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $teachers_creteil,
						'locale' => 'fr_FR',
						),
		'creteil_debutants_2013' => array('belts' => array('jaune', 'orange'),
						'name' => "Débutants Créteil 2013-2014",
                				'days_of_week' => array(2,4),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $teachers_creteil,
						'locale' => 'fr_FR',
						),
		'beuvin_2013' => array('belts' => array('jaune', 'orange', 'verte', 'bleue', 'marron', 'noire'),
						'name' => "Beuvin 2013-2014",
                				'days_of_week' => array(3),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $teachers_creteil,
						'locale' => 'fr_FR',
						),
		'bodyvip_confirmes_2013' => array('belts' => array('marron', 'noire'),
						'name' => "Confirmés Body VIP 2013-2014",
                				'days_of_week' => array(3,6),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $teachers_bodyvip,
						'locale' => 'fr_FR',
						),
		'bodyvip_intermediaires_2013' => array('belts' => array('verte', 'bleue'),
						'name' => "Intermédiaires Body VIP 2013-2014",
                				'days_of_week' => array(2,3,6),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $teachers_bodyvip,
						'locale' => 'fr_FR',
						),
		'bodyvip_debutants_2013' => array('belts' => array('jaune', 'orange'),
						'name' => "Débutants Body VIP 2013-2014",
                				'days_of_week' => array(2,3,6),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $teachers_bodyvip,
						'locale' => 'fr_FR',
						),
				);
