<?php

$all_teachers = array("Arnaud", "Cédric", "Cédrico", "Jérôme", "Léo", "Mario", "Séna", "Tefy", "Véronique"),

$lessons = array(
		'creteil_confirmes_2013' => array('belts' => array('marron', 'noire'),
						'name' => "Confirmés Créteil 2013-2014",
                				'days_of_week' => array(2,4),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $all_teachers,,
						'locale' => 'fr_FR',
						),
		'creteil_intermediaires_2013' => array('belts' => array('verte', 'bleue'),
						'name' => "Intermédiaires Créteil 2013-2014",
                				'days_of_week' => array(2,5),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $all_teachers,
						'locale' => 'fr_FR',
						),
		'creteil_debutants_2013' => array('belts' => array('jaune', 'orange'),
						'name' => "Débutants Créteil 2013-2014",
                				'days_of_week' => array(2,4),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $all_teachers,
						'locale' => 'fr_FR',
						),
		'beuvin_2013' => array('belts' => array('jaune', 'orange'),
						'name' => "Beuvin 2013-2014",
                				'days_of_week' => array(3),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $all_teachers,
						'locale' => 'fr_FR',
						),
		'bodyvip_confirmes_2013' => array('belts' => array('marron', 'noire'),
						'name' => "Confirmés Body VIP 2013-2014",
                				'days_of_week' => array(3,6),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $all_teachers,
						'locale' => 'fr_FR',
						),
		'bodyvip_intermediaires_2013' => array('belts' => array('verte', 'bleue'),
						'name' => "Intermédiaires Body VIP 2013-2014",
                				'days_of_week' => array(2,3,6),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $all_teachers,
						'locale' => 'fr_FR',
						),
		'bodyvip_debutants_2013' => array('belts' => array('jaune', 'orange'),
						'name' => "Débutants Body VIP 2013-2014",
                				'days_of_week' => array(2,3,6),
                				'start_date' => "2013-09-10",
						'end_date' => "2014-06-20",
						'teachers' => $all_teachers,
						'locale' => 'fr_FR',
						),
				);
